export const menuItems = [
  { name: 'Home', link: '/' },
  { name: 'Discover Photos', link: '/discover' },
  { name: 'Popular Searches', link: '/popular' },
  { name: 'Free Videos', link: '/videos' },
  { name: 'Challenges', link: '/challenges' },
  { name: 'Leaderboard', link: '/leaderboard' },
  { name: 'Pexels Blog', link: '/blog' },
  { name: 'Your Profile', link: '/profile' },
  { name: 'Change Language', link: '/language' },
  { name: 'Upload', link: '/upload' },
  { name: 'License', link: '/license' },
  { name: 'Settings', link: '/settings' },
  { name: 'Logout', link: '/logout' },
  { name: 'Apps & Plugins', link: '/apps' },
  { name: 'FAQ', link: '/faq' },
  { name: 'About Us', link: '/about' },
  { name: 'Imprint & Terms', link: '/terms' },
]
